# Generated by Django 4.2.4 on 2023-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_time_delete_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='mail_id',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
