# Generated by Django 4.2.4 on 2023-08-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email_id',
            new_name='Mail_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='Salary',
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
